-- lib.test.fn() creates a callable mock that records every call.
-- It supports mockReturnValue, mockImplementation, mockClear, mockReset.

lib.test.describe('mock functions (lib.test.fn)', function()
    lib.test.it('records calls and arguments', function()
        local m = lib.test.fn()
        m('alice', 1)
        m('bob', 2)
        lib.test.expect(m):toHaveBeenCalled()
        lib.test.expect(m):toHaveBeenCalledTimes(2)
        lib.test.expect(m):toHaveBeenCalledWith('alice', 1)
        lib.test.expect(m.calls):toHaveLength(2)
        lib.test.expect(m.lastCall):toEqual({ 'bob', 2 })
    end)

    lib.test.it('mockReturnValue overrides return', function()
        local m = lib.test.fn():mockReturnValue(99)
        lib.test.expect(m()):toBe(99)
        lib.test.expect(m('ignored')):toBe(99)
    end)

    lib.test.it('fn(impl) accepts an implementation in the constructor', function()
        local m = lib.test.fn(function(x) return x + 1 end)
        lib.test.expect(m(10)):toBe(11)
        lib.test.expect(m):toHaveBeenCalledWith(10)
    end)

    lib.test.it('mockImplementation runs custom logic', function()
        local m = lib.test.fn():mockImplementation(function(a, b) return a * b end)
        lib.test.expect(m(3, 4)):toBe(12)
        lib.test.expect(m):toHaveBeenCalledWith(3, 4)
    end)

    lib.test.it('toHaveBeenCalledTimes(0) holds for an unused mock', function()
        local m = lib.test.fn()
        lib.test.expect(m):toHaveBeenCalledTimes(0)
        lib.test.expect(m).never:toHaveBeenCalled()
    end)

    lib.test.it('.never:toHaveBeenCalledWith asserts a specific call did not happen', function()
        local m = lib.test.fn()
        m('alice')
        m('bob')
        lib.test.expect(m).never:toHaveBeenCalledWith('carol')
        lib.test.expect(m):toHaveBeenCalledWith('alice')
    end)

    lib.test.it('mockClear wipes call history but keeps impl', function()
        local m = lib.test.fn():mockReturnValue('x')
        m(); m(); m()
        m:mockClear()
        lib.test.expect(m.callCount):toBe(0)
        lib.test.expect(m()):toBe('x')
    end)

    lib.test.it('mockReset wipes everything including impl', function()
        local m = lib.test.fn():mockReturnValue('x')
        m()
        m:mockReset()
        lib.test.expect(m.callCount):toBe(0)
        lib.test.expect(m()):toBeNil()
    end)

end)
